### ISSUE TITLE
pytz.exceptions.UnknownTimeZoneError: '/freeassociation.sourceforge.net/Europe/Zurich'

### ISSUE THREAD

**Issue by oatmealm** [chmouel/gnome-next-meeting-applet#17]
* Gnome Next Meeting applet version:
* Python version: 3.10.0
* Operating System: Fedora 35

### Description

Nothing happens when launching the applet. When I run it from the command line, I'm seeing the error about incorrect timezone.

### What I Did

```
(gnome-next-meeting-applet:5421): e-data-server-CRITICAL **: 09:49:24.634: client_set_source: assertion 'E_IS_SOURCE (source)' failed

(gnome-next-meeting-applet:5421): e-data-server-CRITICAL **: 09:49:24.638: client_set_source: assertion 'E_IS_SOURCE (source)' failed

(gnome-next-meeting-applet:5421): e-data-server-CRITICAL **: 09:49:24.642: client_set_source: assertion 'E_IS_SOURCE (source)' failed
Traceback (most recent call last):
  File "/usr/bin/gnome-next-meeting-applet", line 33, in <module>
    sys.exit(load_entry_point('gnome-next-meeting-applet==1.6.0', 'console_scripts', 'gnome-next-meeting-applet')())
  File "/usr/lib/python3.10/site-packages/gnome_next_meeting_applet/cli.py", line 8, in main
    gnma.run()
  File "/usr/lib/python3.10/site-packages/gnome_next_meeting_applet/applet.py", line 368, in run
    c.main()
  File "/usr/lib/python3.10/site-packages/gnome_next_meeting_applet/applet.py", line 363, in main
    self.build_indicator()
  File "/usr/lib/python3.10/site-packages/gnome_next_meeting_applet/applet.py", line 356, in build_indicator
    self.make_menu_items()
  File "/usr/lib/python3.10/site-packages/gnome_next_meeting_applet/applet.py", line 209, in make_menu_items
    self.events = self.get_all_events()
  File "/usr/lib/python3.10/site-packages/gnome_next_meeting_applet/applet.py", line 123, in get_all_events
    event_list = evolutionCalendar.get_all_events(
  File "/usr/lib/python3.10/site-packages/gnome_next_meeting_applet/evolution_calendars.py", line 93, in get_all_events
    events += self._get_gnome_events_from_calendar_source(source)
  File "/usr/lib/python3.10/site-packages/gnome_next_meeting_applet/evolution_calendars.py", line 67, in _get_gnome_events_from_calendar_source
    start_time = get_ecal_as_utc(value.get_dtstart())
  File "/usr/lib/python3.10/site-packages/gnome_next_meeting_applet/evolution_calendars.py", line 27, in get_ecal_as_utc
    tz = pytz.timezone(ecalcomp.get_tzid() or "UTC")
  File "/usr/lib/python3.10/site-packages/pytz/__init__.py", line 176, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: '/freeassociation.sourceforge.net/Europe/Zurich'
```

**Comment by chmouel** [comment]
oh i was just reading this code in gnome-calendar referring to it in gnome-calendar, 

did you edit/save some events in gnome-calendar right?

**Comment by chmouel** [comment]
found the same issue here https://github.com/owncloud/core/issues/4428 

will issue a workaround...
