### ISSUE TITLE
Module 'gnome_next_meeting_applet.applet' has no attribute 'CREDENTIALS_PATH'

### ISSUE THREAD

**Issue by imamulakhyar93** [chmouel/gnome-next-meeting-applet#2]
* Gnome Next Meeting applet version: 0.3.0-1~focal1
* Python version: 3.8.5
* Operating System: Ubuntu 20.04.2 TLS

### Description

Couldn't start the application

### What I Did
I tried to open using the credential as mentioned in the README file. But i get the following error:
```sh
$ gnome-next-meeting-applet-auth ~/Documents/next-meeting.json

Traceback (most recent call last):
  File "/usr/bin/gnome-next-meeting-applet-auth", line 11, in <module>
    load_entry_point('gnome-next-meeting-applet==0.1.0', 'console_scripts', 'gnome-next-meeting-applet-auth')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/gnome_next_meeting_applet/auth.py", line 24, in <module>
    import gnome_next_meeting_applet.applet as gnma
  File "/usr/lib/python3/dist-packages/gnome_next_meeting_applet/applet.py", line 32, in <module>
    from gi.repository import AppIndicator3 as appindicator
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 132, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name AppIndicator3, introspection typelib not found
```
then I installed the missing lib by `sudo apt install libappindicator3-dev`

After that I tried to run it again, but the following error is occurred:
```sh
$ gnome-next-meeting-applet-auth ~/Documents/next-meeting.json

/usr/lib/python3/dist-packages/gnome_next_meeting_applet/applet.py:32: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
Traceback (most recent call last):
  File "/usr/bin/gnome-next-meeting-applet-auth", line 11, in <module>
    load_entry_point('gnome-next-meeting-applet==0.1.0', 'console_scripts', 'gnome-next-meeting-applet-auth')()
  File "/usr/lib/python3/dist-packages/gnome_next_meeting_applet/auth.py", line 46, in main
    dpath = pathlib.Path(gnma.CREDENTIALS_PATH)
AttributeError: module 'gnome_next_meeting_applet.applet' has no attribute 'CREDENTIALS_PATH'
```

What am I missing?

**Comment by harshit-gangal** [comment]
I also see the similar error. After installing `sudo apt install libappindicator3-dev`. I see the below error.

```
/usr/lib/python3/dist-packages/gnome_next_meeting_applet/applet.py:32: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
Credential has not been configured you need to launch  gnome-next-meeting-applet-auth

```

**Comment by joseph-lozano** [comment]
I am also having this issue 
```
/usr/lib/python3/dist-packages/gnome_next_meeting_applet/applet.py:32: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
Traceback (most recent call last):
  File "/usr/bin/gnome-next-meeting-applet-auth", line 33, in <module>
    sys.exit(load_entry_point('gnome-next-meeting-applet==0.1.0', 'console_scripts', 'gnome-next-meeting-applet-auth')())
  File "/usr/lib/python3/dist-packages/gnome_next_meeting_applet/auth.py", line 46, in main
    dpath = pathlib.Path(gnma.CREDENTIALS_PATH)
AttributeError: module 'gnome_next_meeting_applet.applet' has no attribute 'CREDENTIALS_PATH'
```

**Comment by akhyar93** [comment]
Maybe this can help you, I made similar one https://github.com/akhyar93/next-meeting :bow:

**Comment by dorianbrown** [comment]
Same issue here!

**Comment by dorianbrown** [comment]
I decided to just fix it, changes are in this [PR](https://github.com/chmouel/gnome-next-meeting-applet/pull/3).

It would be great if a fix could get merged, but otherwise I'll if I can get the publishing of my fork working so that this awesome application can be used by more people!
