### ISSUE TITLE
Won't start due to "The 'dbus-python<2.0.0,>=1.2.18' distribution was not found"

### ISSUE THREAD

**Issue by dwrBad** [chmouel/gnome-next-meeting-applet#26]
* Gnome Next Meeting applet version:  2.5.0-1
* Python version:  3.10.1-2
* Operating System: manjaro

### Description
It won't start anymore complaing about:

```
Traceback (most recent call last):
  File "/usr/bin/gnome-next-meeting-applet", line 33, in <module>
    sys.exit(load_entry_point('gnome-next-meeting-applet==2.5.0', 'console_scripts', 'gnome-next-meeting-applet')())
  File "/usr/bin/gnome-next-meeting-applet", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/gnma/cli.py", line 5, in <module>
    from gnma import applet, dbusclient
  File "/usr/lib/python3.10/site-packages/gnma/applet.py", line 22, in <module>
    from gnma import strings
  File "/usr/lib/python3.10/site-packages/gnma/strings.py", line 4, in <module>
    import humanize
  File "/usr/lib/python3.10/site-packages/humanize/__init__.py", line 2, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dbus-python<2.0.0,>=1.2.18' distribution was not found and is required by gnome-next-meeting-applet
```

though dbus-python is: 
```
❯ pacman -Q --info dbus-python
Name            : dbus-python
Version         : 1.2.18-3
```

**Comment by chmouel** [comment]
Thanks for the bug report, you did install from the AUR right?

**Comment by dwrBad** [comment]
Yes, that's correct

**Comment by chmouel** [comment]
seems to be fixed in -2 release 

cf: https://aur.archlinux.org/cgit/aur.git/commit/?h=gnome-next-meeting-applet&id=87964a10c62e403b11691ef0eedf238ab5fe2048

i guess if you update it will work again! (it does for me)

**Comment by dwrBad** [comment]
Thanks a lot, that fixed it.
