### ISSUE TITLE
IndexError: list index out of range at text = event.get_descriptions()[0].get_value()

### ISSUE THREAD

**Issue by GabLeRoux** [chmouel/gnome-next-meeting-applet#7]
* Gnome Next Meeting applet version: 1.1.0-1~focal1
* Python version: 3.8.8
* Operating System: Ubuntu 20.04.3 LTS

### Description

```
gnome-next-meeting-applet --version
/usr/lib/python3/dist-packages/gnome_next_meeting_applet/applet.py:27: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator

(gnome-next-meeting-applet:607139): e-data-server-CRITICAL **: 12:16:18.467: client_set_source: assertion 'E_IS_SOURCE (source)' failed

(gnome-next-meeting-applet:607139): e-data-server-CRITICAL **: 12:16:18.530: client_set_source: assertion 'E_IS_SOURCE (source)' failed

(gnome-next-meeting-applet:607139): e-data-server-CRITICAL **: 12:16:18.540: client_set_source: assertion 'E_IS_SOURCE (source)' failed

(gnome-next-meeting-applet:607139): e-data-server-CRITICAL **: 12:16:18.798: client_set_source: assertion 'E_IS_SOURCE (source)' failed

(gnome-next-meeting-applet:607139): e-data-server-CRITICAL **: 12:16:18.816: client_set_source: assertion 'E_IS_SOURCE (source)' failed

(gnome-next-meeting-applet:607139): e-data-server-CRITICAL **: 12:16:18.843: client_set_source: assertion 'E_IS_SOURCE (source)' failed

(gnome-next-meeting-applet:607139): e-data-server-CRITICAL **: 12:16:18.850: client_set_source: assertion 'E_IS_SOURCE (source)' failed

(gnome-next-meeting-applet:607139): e-data-server-CRITICAL **: 12:16:18.858: client_set_source: assertion 'E_IS_SOURCE (source)' failed
Traceback (most recent call last):
  File "/usr/bin/gnome-next-meeting-applet", line 11, in <module>
    load_entry_point('gnome-next-meeting-applet==1.1.0', 'console_scripts', 'gnome-next-meeting-applet')()
  File "/usr/lib/python3/dist-packages/gnome_next_meeting_applet/cli.py", line 8, in main
    gnma.run()
  File "/usr/lib/python3/dist-packages/gnome_next_meeting_applet/applet.py", line 353, in run
    c.main()
  File "/usr/lib/python3/dist-packages/gnome_next_meeting_applet/applet.py", line 348, in main
    self.build_indicator()
  File "/usr/lib/python3/dist-packages/gnome_next_meeting_applet/applet.py", line 339, in build_indicator
    self.make_menu_items()
  File "/usr/lib/python3/dist-packages/gnome_next_meeting_applet/applet.py", line 268, in make_menu_items
    match_videocall_summary = self._match_videocall_url_from_summary(
  File "/usr/lib/python3/dist-packages/gnome_next_meeting_applet/applet.py", line 304, in _match_videocall_url_from_summary
    text = event.get_descriptions()[0].get_value()
IndexError: list index out of range
```

### What I Did

```
sudo add-apt-repository ppa:chmouel/gnome-next-meeting-applet
sudo apt-get -y install gnome-next-meeting-applet
gnome-next-meeting-applet
```

**Comment by logix2** [comment]
I also got this error. It appears that this happens when there's no conference link. Once I add a conference link, this works.

**Comment by chmouel** [comment]
Added a quick fix for it! which should hopefully fix it, will do a release soon after,
